// data.ts
import { EgyptData, Translations } from './types';

// Centralized data for all governorates and places in Egypt.
// NOTE: For demonstration, only Cairo, Giza, and Luxor are fully populated. 
// Other governorates are included with placeholder names to show the full list.
export const EGYPT_DATA: EgyptData = {
  cairo: {
    id: 'cairo',
    name: { en: 'Cairo', fr: 'Le Caire', ar: 'القاهرة', it: 'Il Cairo', de: 'Kairo', ru: 'Каир' },
    heritage: [
      {
        id: 'cai-h-1',
        name: { en: 'The Egyptian Museum', fr: 'Le Musée égyptien', ar: 'المتحف المصري', it: 'Il Museo Egizio', de: 'Das Ägyptische Museum', ru: 'Египетский музей' },
        images: ['https://images.picsum.photos/id/1/1024/768.jpg', 'https://images.picsum.photos/id/2/1024/768.jpg', 'https://images.picsum.photos/id/3/1024/768.jpg'],
        shortDescription: { en: 'Home to an extensive collection of ancient Egyptian antiquities.', fr: 'Abrite une vaste collection d\'antiquités égyptiennes.', ar: 'يضم مجموعة واسعة من الآثار المصرية القديمة.', it: 'Ospita una vasta collezione di antichità dell\'antico Egitto.', de: 'Beherbergt eine umfangreiche Sammlung altägyptischer Altertümer.', ru: 'Хранилище обширной коллекции древнеегипетских артефактов.' },
        longDescription: { en: 'Located in Tahrir Square, the Egyptian Museum houses over 120,000 artifacts. It is one of the largest and most spectacular museums in the region, featuring the famous collection of Tutankhamun.', fr: 'Situé sur la place Tahrir, le musée égyptien abrite plus de 120 000 objets. C\'est l\'un des musées les plus grands et les plus spectaculaires de la région, avec la célèbre collection de Toutankhamon.', ar: 'يقع المتحف المصري في ميدان التحرير، ويضم أكثر من 120 ألف قطعة أثرية. إنه أحد أكبر وأروع المتاحف في المنطقة، ويضم مجموعة توت عنخ آمون الشهيرة.', it: 'Situato in Piazza Tahrir, il Museo Egizio ospita oltre 120.000 reperti. È uno dei musei più grandi e spettacolari della regione, con la famosa collezione di Tutankhamon.', de: 'Das Ägyptische Museum am Tahrir-Platz beherbergt über 120.000 Artefakte. Es ist eines der größten und spektakulärsten Museen der Region und zeigt die berühmte Sammlung von Tutanchamun.', ru: 'Расположенный на площади Тахрир, Египетский музей хранит более 120 000 артефактов. Это один из крупнейших и самых впечатляющих музеев в регионе, в котором представлена знаменитая коллекция Тутанхамона.' },
        rating: 4.8,
        googleMapsUrl: 'https://maps.app.goo.gl/kG1YJ4x2qZ8e7f6t5',
        contactNumber: '+20 2 25796948'
      },
      {
        id: 'cai-h-2',
        name: { en: 'Khan el-Khalili', fr: 'Khan el-Khalili', ar: 'خان الخليلي', it: 'Khan el-Khalili', de: 'Chan el-Chalili', ru: 'Хан эль-Халили' },
        images: ['https://images.picsum.photos/id/4/1024/768.jpg', 'https://images.picsum.photos/id/5/1024/768.jpg', 'https://images.picsum.photos/id/6/1024/768.jpg'],
        shortDescription: { en: 'A famous bazaar and souq in the historic center of Cairo.', fr: 'Un célèbre bazar et souk dans le centre historique du Caire.', ar: 'بازار وسوق شهير في وسط القاهرة التاريخي.', it: 'Un famoso bazar e souq nel centro storico del Cairo.', de: 'Ein berühmter Basar und Suq im historischen Zentrum von Kairo.', ru: 'Знаменитый базар и рынок в историческом центре Каира.' },
        longDescription: { en: 'Established in the 14th century, Khan el-Khalili is a bustling open-air bazaar filled with unique items, from spices and perfumes to jewelry and souvenirs. It represents the heart of old Cairo\'s commercial activities.', fr: 'Fondé au XIVe siècle, Khan el-Khalili est un bazar en plein air animé rempli d\'articles uniques, des épices et parfums aux bijoux et souvenirs. Il représente le cœur des activités commerciales du vieux Caire.', ar: 'تأسس خان الخليلي في القرن الرابع عشر، وهو بازار مفتوح يعج بالبضائع الفريدة، من التوابل والعطور إلى المجوهرات والهدايا التذكارية. إنه يمثل قلب الأنشطة التجارية في القاهرة القديمة.', it: 'Fondato nel XIV secolo, Khan el-Khalili è un vivace bazar all\'aperto pieno di oggetti unici, dalle spezie e profumi ai gioielli e souvenir. Rappresenta il cuore delle attività commerciali della vecchia Cairo.', de: 'Gegründet im 14. Jahrhundert, ist Chan el-Chalili ein belebter Freiluftbasar voller einzigartiger Gegenstände, von Gewürzen und Parfums bis hin zu Schmuck und Souvenirs. Er repräsentiert das Herz der kommerziellen Aktivitäten des alten Kairo.', ru: 'Основанный в 14 веке, Хан эль-Халили — это оживленный открытый базар, наполненный уникальными товарами, от специй и парфюмерии до ювелирных изделий и сувениров. Он представляет собой сердце коммерческой деятельности старого Каира.' },
        rating: 4.6,
        googleMapsUrl: 'https://maps.app.goo.gl/uQ7X3xZ4sY5p2f6w6',
      },
       {
        id: 'cai-h-3',
        name: { en: 'Al-Azhar Mosque', fr: 'Mosquée Al-Azhar', ar: 'الجامع الأزهر', it: 'Moschea di al-Azhar', de: 'Al-Azhar-Moschee', ru: 'Мечеть аль-Азхар' },
        images: ['https://images.picsum.photos/id/101/1024/768.jpg', 'https://images.picsum.photos/id/102/1024/768.jpg'],
        shortDescription: { en: 'A historic mosque and the first Fatimid university in the world.', fr: 'Une mosquée historique et la première université fatimide au monde.', ar: 'مسجد تاريخي وأول جامعة فاطمية في العالم.', it: 'Una moschea storica e la prima università fatimide al mondo.', de: 'Eine historische Moschee und die erste Fatimiden-Universität der Welt.', ru: 'Историческая мечеть и первый фатимидский университет в мире.' },
        longDescription: { en: 'Founded in 970, Al-Azhar Mosque is one of Cairo\'s earliest. It later became a university, one of the oldest in the world, and has remained a center for Islamic learning and scholarship for over a millennium. Its architecture is a beautiful mix of styles from various dynasties.', fr: 'Fondée en 970, la mosquée Al-Azhar est l\'une des plus anciennes du Caire. Elle est ensuite devenue une université, l\'une des plus anciennes au monde, et est restée un centre d\'apprentissage et d\'érudition islamiques pendant plus d\'un millénaire. Son architecture est un magnifique mélange de styles de différentes dynasties.', ar: 'تأسس الجامع الأزهر عام 970، وهو من أقدم مساجد القاهرة. وأصبح فيما بعد جامعة، من أقدم جامعات العالم، وظل مركزاً للتعليم الإسلامي والدراسات الإسلامية لأكثر من ألف عام. هندسته المعمارية هي مزيج جميل من الأساليب من مختلف السلالات.', it: 'Fondata nel 970, la Moschea di al-Azhar è una delle più antiche del Cairo. In seguito divenne un\'università, una delle più antiche del mondo, ed è rimasta per oltre un millennio un centro di apprendimento e di cultura islamica. La sua architettura è un bellissimo mix di stili di varie dinastie.', de: 'Die 970 gegründete Al-Azhar-Moschee ist eine der frühesten in Kairo. Sie wurde später zu einer Universität, einer der ältesten der Welt, und ist seit über einem Jahrtausend ein Zentrum für islamisches Lernen und Gelehrsamkeit. Ihre Architektur ist eine wunderschöne Mischung aus Stilen verschiedener Dynastien.', ru: 'Основанная в 970 году, мечеть аль-Азхар является одной из старейших в Каире. Позже она стала университетом, одним из старейших в мире, и на протяжении более тысячелетия оставалась центром исламского образования и науки. Ее архитектура представляет собой прекрасное сочетание стилей различных династий.' },
        rating: 4.8,
        googleMapsUrl: 'https://maps.app.goo.gl/3q2aH3sX8y7z9F6v7',
      },
    ],
    restaurants: [
      {
        id: 'cai-r-1',
        name: { en: 'Abou El Sid', fr: 'Abou El Sid', ar: 'أبو السيد', it: 'Abou El Sid', de: 'Abou El Sid', ru: 'Абу Эль Сид' },
        images: ['https://images.picsum.photos/id/10/1024/768.jpg', 'https://images.picsum.photos/id/11/1024/768.jpg'],
        shortDescription: { en: 'Authentic Egyptian cuisine in an ornate, traditional setting.', fr: 'Cuisine égyptienne authentique dans un cadre orné et traditionnel.', ar: 'مأكولات مصرية أصيلة في أجواء تقليدية مزخرفة.', it: 'Autentica cucina egiziana in un ambiente ornato e tradizionale.', de: 'Authentische ägyptische Küche in einem kunstvollen, traditionellen Ambiente.', ru: 'Аутентичная египетская кухня в богато украшенной традиционной обстановке.' },
        longDescription: { en: 'Abou El Sid offers a unique dining experience, transporting you to old-world Cairo with its decor and classic Egyptian dishes. It is renowned for its authentic flavors and romantic atmosphere, perfect for a memorable meal.', fr: 'Abou El Sid offre une expérience culinaire unique, vous transportant dans le Caire d\'antan avec son décor and ses plats égyptiens classiques. Il est réputé pour ses saveurs authentiques et son atmosphère romantique, parfait pour un repas mémorable.', ar: 'يقدم أبو السيد تجربة طعام فريدة من نوعها، حيث ينقلك إلى القاهرة القديمة بديكوراته وأطباقه المصرية الكلاسيكية. يشتهر بنكهاته الأصيلة وأجوائه الرومانسية، وهو مثالي لوجبة لا تُنسى.', it: 'Abou El Sid offre un\'esperienza culinaria unica, trasportandoti nella vecchia Cairo con il suo arredamento e i suoi piatti classici egiziani. È rinomato per i suoi sapori autentici e l\'atmosfera romantica, perfetto per un pasto memorabile.', de: 'Abou El Sid bietet ein einzigartiges kulinarisches Erlebnis, das Sie mit seiner Einrichtung und den klassischen ägyptischen Gerichten in die alte Welt Kairos versetzt. Es ist bekannt für seine authentischen Aromen und seine romantische Atmosphäre, perfekt für ein unvergessliches Essen.', ru: 'Abou El Sid предлагает уникальный гастрономический опыт, перенося вас в старый Каир с его декором и классическими египетскими блюдами. Он известен своими аутентичными вкусами и романтической атмосферой, идеально подходящей для незабываемого ужина.' },
        rating: 4.5,
        averagePrice: '$$$',
        googleMapsUrl: 'https://maps.app.goo.gl/9tHq8fX7uY6o9zGk7',
        contactNumber: '+20 2 27359640'
      },
      {
        id: 'cai-r-2',
        name: { en: 'Koshary Abou Tarek', fr: 'Koshary Abou Tarek', ar: 'كشري أبو طارق', it: 'Koshary Abou Tarek', de: 'Koshary Abou Tarek', ru: 'Кошари Абу Тарек' },
        images: ['https://images.picsum.photos/id/111/1024/768.jpg', 'https://images.picsum.photos/id/112/1024/768.jpg'],
        shortDescription: { en: 'Famous for serving one of Egypt\'s most beloved national dishes, Koshary.', fr: 'Célèbre pour servir l\'un des plats nationaux les plus appréciés d\'Égypte, le Koshary.', ar: 'يشتهر بتقديم أحد أشهر الأطباق الوطنية في مصر، الكشري.', it: 'Famoso per servire uno dei piatti nazionali più amati d\'Egitto, il Koshary.', de: 'Berühmt für eines der beliebtesten Nationalgerichte Ägyptens, Koshary.', ru: 'Знаменит подачей одного из самых любимых национальных блюд Египта — кошари.' },
        longDescription: { en: 'A legendary institution in downtown Cairo, Abou Tarek is dedicated to perfecting a single dish: koshary. This hearty mix of rice, lentils, pasta, and chickpeas topped with a spicy tomato sauce and fried onions is a must-try for any visitor.', fr: 'Institution légendaire du centre-ville du Caire, Abou Tarek se consacre à perfectionner un seul plat : le koshary. Ce mélange copieux de riz, de lentilles, de pâtes et de pois chiches, garni d\'une sauce tomate épicée et d\'oignons frits, est un incontournable pour tout visiteur.', ar: 'يعتبر أبو طارق مؤسسة أسطورية في وسط القاهرة، وهو مكرس لإتقان طبق واحد: الكشري. هذا المزيج الشهي من الأرز والعدس والمعكرونة والحمص مع صلصة الطماطم الحارة والبصل المقلي أمر لا بد منه لأي زائر.', it: 'Un\'istituzione leggendaria nel centro del Cairo, Abou Tarek si dedica a perfezionare un unico piatto: il koshary. Questo sostanzioso mix di riso, lenticchie, pasta e ceci condito con una salsa di pomodoro piccante e cipolle fritte è un must per ogni visitatore.', de: 'Als legendäre Institution in der Innenstadt von Kairo hat sich Abou Tarek der Perfektionierung eines einzigen Gerichts verschrieben: Koshary. Diese herzhafte Mischung aus Reis, Linsen, Nudeln und Kichererbsen, garniert mit einer würzigen Tomatensauce und Röstzwiebeln, ist ein Muss für jeden Besucher.', ru: 'Легендарное заведение в центре Каира, Абу Тарек посвятил себя совершенствованию одного блюда: кошари. Это сытное сочетание риса, чечевицы, макарон и нута, политое острым томатным соусом и жареным луком, обязательно к пробе для любого гостя.' },
        rating: 4.6,
        averagePrice: '$',
        googleMapsUrl: 'https://maps.app.goo.gl/9rPqZJm5yN3hB4k86',
        contactNumber: '+20 2 25775935'
      },
    ],
    cafes: [
       {
        id: 'cai-c-1',
        name: { en: 'El Fishawy Cafe', fr: 'Café El Fishawy', ar: 'قهوة الفيشاوي', it: 'Caffè El Fishawy', de: 'El Fishawy Café', ru: 'Кафе Эль-Фишави' },
        images: ['https://images.picsum.photos/id/20/1024/768.jpg', 'https://images.picsum.photos/id/21/1024/768.jpg'],
        shortDescription: { en: 'One of Cairo\'s oldest and most famous cafes in Khan el-Khalili.', fr: 'L\'un des cafés les plus anciens et les plus célèbres du Caire à Khan el-Khalili.', ar: 'أحد أقدم وأشهر المقاهي في القاهرة في خان الخليلي.', it: 'Uno dei caffè più antichi e famosi del Cairo a Khan el-Khalili.', de: 'Eines der ältesten und berühmtesten Cafés in Kairo in Chan el-Chalili.', ru: 'Одно из старейших и самых известных кафе Каира в Хан эль-Халили.' },
        longDescription: { en: 'Operating since 1797, El Fishawy is a historic landmark. Adorned with large mirrors and antique furniture, it has been a meeting place for writers, artists, and intellectuals for centuries, including the Nobel laureate Naguib Mahfouz.', fr: 'Ouvert depuis 1797, El Fishawy est un monument historique. Orné de grands miroirs et de meubles anciens, il a été un lieu de rencontre pour les écrivains, les artistes et les intellectuels pendant des siècles, dont le lauréat du prix Nobel Naguib Mahfouz.', ar: 'يعمل مقهى الفيشاوي منذ عام 1797، وهو معلم تاريخي. تم تزيينه بمرايا كبيرة وأثاث عتيق، وكان مكانًا للقاء الكتاب والفنانين والمثقفين لقرون، بما في ذلك نجيب محفوظ الحائز على جائزة نوبل.', it: 'Operativo dal 1797, El Fishawy è un punto di riferimento storico. Adornato con grandi specchi e mobili antichi, è stato per secoli un luogo di incontro per scrittori, artisti e intellettuali, tra cui il premio Nobel Naguib Mahfouz.', de: 'Das seit 1797 betriebene El Fishawy ist ein historisches Wahrzeichen. Geschmückt mit großen Spiegeln und antiken Möbeln, war es jahrhundertelang ein Treffpunkt für Schriftsteller, Künstler und Intellektuelle, einschließlich des Nobelpreisträgers Naguib Mahfouz.', ru: 'Работающее с 1797 года, кафе Эль-Фишави является исторической достопримечательностью. Украшенное большими зеркалами и антикварной мебелью, оно на протяжении веков было местом встреч писателей, художников и интеллектуалов, включая нобелевского лауреата Нагиба Махфуза.' },
        rating: 4.4,
        averagePrice: '$$',
        googleMapsUrl: 'https://maps.app.goo.gl/C2rYjL3xZ4w5aB6v7',
      },
    ],
    hotels: [
      {
        id: 'cai-h-1',
        name: { en: 'Marriott Mena House', fr: 'Marriott Mena House', ar: 'فندق ماريوت مينا هاوس', it: 'Marriott Mena House', de: 'Marriott Mena House', ru: 'Marriott Mena House' },
        images: ['https://images.picsum.photos/id/30/1024/768.jpg', 'https://images.picsum.photos/id/31/1024/768.jpg'],
        shortDescription: { en: 'A historic palace hotel with spectacular views of the pyramids.', fr: 'Un hôtel-palais historique avec des vues spectaculaires sur les pyramides.', ar: 'فندق قصر تاريخي بإطلالات خلابة على الأهرامات.', it: 'Un hotel storico in un palazzo con viste spettacolari sulle piramidi.', de: 'Ein historisches Palasthotel mit spektakulärem Blick auf die Pyramiden.', ru: 'Исторический дворец-отель с захватывающим видом на пирамиды.' },
        longDescription: { en: 'Originally a royal hunting lodge, the Marriott Mena House combines historic charm with modern luxury. Guests can enjoy lush gardens, exquisite dining, and unparalleled views of the Great Pyramids of Giza, offering a truly once-in-a-lifetime experience.', fr: 'À l\'origine un pavillon de chasse royal, le Marriott Mena House allie le charme historique au luxe moderne. Les clients peuvent profiter de jardins luxuriants, de restaurants exquis et de vues incomparables sur les grandes pyramides de Gizeh, offrant une expérience vraiment unique.', ar: 'كان فندق ماريوت مينا هاوس في الأصل نزل صيد ملكي، ويجمع بين السحر التاريخي والفخامة الحديثة. يمكن للضيوف الاستمتاع بالحدائق المورقة وتناول الطعام الرائع والإطلالات التي لا مثيل لها على أهرامات الجيزة العظيمة، مما يوفر تجربة فريدة من نوعها حقًا.', it: 'Originariamente un casino di caccia reale, il Marriott Mena House combina il fascino storico con il lusso moderno. Gli ospiti possono godere di giardini lussureggianti, una cucina squisita e viste impareggiabili sulle Grandi Piramidi di Giza, offrendo un\'esperienza davvero unica nella vita.', de: 'Ursprünglich ein königliches Jagdschloss, verbindet das Marriott Mena House historischen Charme mit modernem Luxus. Die Gäste können üppige Gärten, exquisite Restaurants und einen unvergleichlichen Blick auf die Großen Pyramiden von Gizeh genießen, was ein wirklich einmaliges Erlebnis bietet.', ru: 'Изначально бывший королевским охотничьим домиком, Marriott Mena House сочетает в себе исторический шарм и современную роскошь. Гости могут наслаждаться пышными садами, изысканными блюдами и непревзойденным видом на Великие пирамиды Гизы, что делает пребывание поистине незабываемым.' },
        rating: 4.8,
        averagePrice: '$$$$',
        googleMapsUrl: 'https://maps.app.goo.gl/tZ5fX6w7rYp8L3s9a',
        contactNumber: '+20 2 33773222'
      }
    ]
  },
  giza: {
    id: 'giza',
    name: { en: 'Giza', fr: 'Gizeh', ar: 'الجيزة', it: 'Giza', de: 'Gizeh', ru: 'Гиза' },
    heritage: [
      {
        id: 'giz-h-1',
        name: { en: 'Giza Pyramid Complex', fr: 'Complexe de pyramides de Gizeh', ar: 'مجمع أهرامات الجيزة', it: 'Complesso delle piramidi di Giza', de: 'Pyramidenkomplex von Gizeh', ru: 'Комплекс пирамид в Гизе' },
        images: ['https://images.picsum.photos/id/40/1024/768.jpg', 'https://images.picsum.photos/id/41/1024/768.jpg', 'https://images.picsum.photos/id/42/1024/768.jpg'],
        shortDescription: { en: 'Includes the Great Pyramid, Khafre, Menkaure, and the Great Sphinx.', fr: 'Comprend la Grande Pyramide, Khéphren, Mykérinos et le Grand Sphinx.', ar: 'يضم الهرم الأكبر وخفرع ومنقرع وأبو الهول العظيم.', it: 'Include la Grande Piramide, Chefren, Micerino e la Grande Sfinge.', de: 'Umfasst die Große Pyramide, Chephren, Mykerinos und die Große Sphinx.', ru: 'Включает Великую пирамиду, пирамиды Хефрена, Микерина и Большого Сфинкса.' },
        longDescription: { en: 'The Giza Plateau is one of the most famous archaeological sites in the world. It contains the Great Pyramid of Giza (one of the Seven Wonders of the Ancient World), the somewhat smaller Pyramid of Khafre, the relatively modest-sized Pyramid of Menkaure, along with a number of smaller satellite edifices known as "queens" pyramids, and the Great Sphinx.', fr: 'Le plateau de Gizeh est l\'un des sites archéologiques les plus célèbres au monde. Il contient la Grande Pyramide de Gizeh (l\'une des Sept Merveilles du Monde Antique), la Pyramide de Khéphren un peu plus petite, la Pyramide de Mykérinos de taille relativement modeste, ainsi qu\'un certain nombre d\'édifices satellites plus petits connus sous le nom de pyramides de "reines", et le Grand Sphinx.', ar: 'هضبة الجيزة هي واحدة من أشهر المواقع الأثرية في العالم. تحتوي على هرم خوفو الأكبر (إحدى عجائب الدنيا السبع في العالم القديم)، وهرم خفرع الأصغر حجمًا إلى حد ما، وهرم منقرع المتواضع نسبيًا، إلى جانب عدد من الصروح الصغيرة التابعة المعروفة باسم أهرامات "الملكات"، وأبو الهول العظيم.', it: 'L\'altopiano di Giza è uno dei siti archeologici più famosi al mondo. Contiene la Grande Piramide di Giza (una delle Sette Meraviglie del Mondo Antico), la Piramide di Chefren, leggermente più piccola, la Piramide di Micerino, di dimensioni relativamente modeste, insieme a una serie di edifici satelliti più piccoli noti come piramidi delle "regine", e la Grande Sfinge.', de: 'Das Gizeh-Plateau ist eine der berühmtesten archäologischen Stätten der Welt. Es enthält die Große Pyramide von Gizeh (eines der Sieben Weltwunder der Antike), die etwas kleinere Chephren-Pyramide, die relativ bescheidene Mykerinos-Pyramide sowie eine Reihe kleinerer Satellitenbauten, die als "Königinnen"-Pyramiden bekannt sind, und die Große Sphinx.', ru: 'Плато Гиза — одно из самых известных археологических мест в мире. Здесь находится Великая пирамида Гизы (одно из семи чудес древнего мира), несколько меньшая пирамида Хефрена, относительно скромная пирамида Микерина, а также ряд меньших сооружений-спутников, известных как пирамиды «цариц», и Большой Сфинкс.' },
        rating: 4.9,
        googleMapsUrl: 'https://maps.app.goo.gl/M5dYkR3eW2p4Z1a99',
      },
    ],
    restaurants: [
       {
        id: 'giz-r-1',
        name: { en: '9 Pyramids Lounge', fr: '9 Pyramids Lounge', ar: '9 بيراميدز لاونج', it: '9 Pyramids Lounge', de: '9 Pyramids Lounge', ru: '9 Pyramids Lounge' },
        images: ['https://images.picsum.photos/id/121/1024/768.jpg', 'https://images.picsum.photos/id/122/1024/768.jpg'],
        shortDescription: { en: 'Dine with an unparalleled, direct view of the Giza Pyramids.', fr: 'Dînez avec une vue directe et inégalée sur les pyramides de Gizeh.', ar: 'تناول العشاء مع إطلالة مباشرة لا مثيل لها على أهرامات الجيزة.', it: 'Cenate con una vista diretta e impareggiabile sulle Piramidi di Giza.', de: 'Speisen Sie mit einem unvergleichlichen, direkten Blick auf die Pyramiden von Gizeh.', ru: 'Ужин с непревзойденным, прямым видом на пирамиды Гизы.' },
        longDescription: { en: 'Located directly on the Giza Plateau, this restaurant offers a unique opportunity to enjoy traditional Egyptian breakfast and lunch while gazing at one of the world\'s wonders. It provides a serene atmosphere away from the crowds.', fr: 'Situé directement sur le plateau de Gizeh, ce restaurant offre une occasion unique de savourer un petit-déjeuner et un déjeuner égyptiens traditionnels tout en contemplant l\'une des merveilles du monde. Il offre une atmosphère sereine loin de la foule.', ar: 'يقع هذا المطعم مباشرة على هضبة الجيزة، ويوفر فرصة فريدة للاستمتاع بوجبة الإفطار والغداء المصرية التقليدية أثناء التحديق في إحدى عجائب الدنيا. ويوفر أجواء هادئة بعيدًا عن الزحام.', it: 'Situato direttamente sulla Piana di Giza, questo ristorante offre un\'opportunità unica di gustare la colazione e il pranzo tradizionali egiziani ammirando una delle meraviglie del mondo. Offre un\'atmosfera serena lontano dalla folla.', de: 'Direkt auf dem Gizeh-Plateau gelegen, bietet dieses Restaurant eine einzigartige Gelegenheit, traditionelles ägyptisches Frühstück und Mittagessen zu genießen, während man eines der Weltwunder betrachtet. Es bietet eine ruhige Atmosphäre abseits der Menschenmassen.', ru: 'Расположенный прямо на плато Гиза, этот ресторан предлагает уникальную возможность насладиться традиционным египетским завтраком и обедом, любуясь одним из чудес света. Он создает спокойную атмосферу вдали от толпы.' },
        rating: 4.7,
        averagePrice: '$$$',
        googleMapsUrl: 'https://maps.app.goo.gl/9yV9tYgXkFz6cR3w7',
      },
    ],
    cafes: [],
    hotels: [
       {
        id: 'giz-h-1',
        name: { en: 'Steigenberger Pyramids Cairo', fr: 'Steigenberger Pyramids Cairo', ar: 'فندق شتيجنبرجر بيراميدز القاهرة', it: 'Steigenberger Pyramids Cairo', de: 'Steigenberger Pyramids Cairo', ru: 'Steigenberger Pyramids Cairo' },
        images: ['https://images.picsum.photos/id/131/1024/768.jpg', 'https://images.picsum.photos/id/132/1024/768.jpg'],
        shortDescription: { en: 'Modern hotel offering fantastic views of the pyramids and the Grand Egyptian Museum.', fr: 'Hôtel moderne offrant des vues fantastiques sur les pyramides et le Grand Musée Égyptien.', ar: 'فندق حديث يوفر إطلالات رائعة على الأهرامات والمتحف المصري الكبير.', it: 'Hotel moderno che offre fantastiche viste sulle piramidi e sul Grande Museo Egizio.', de: 'Modernes Hotel mit fantastischem Blick auf die Pyramiden und das Große Ägyptische Museum.', ru: 'Современный отель с фантастическим видом на пирамиды и Большой Египетский музей.' },
        longDescription: { en: 'This hotel is ideally located between the Giza Pyramids and the new Grand Egyptian Museum. It features modern rooms, a large swimming pool, and various dining options, making it a perfect base for exploring the ancient wonders of Giza.', fr: 'Cet hôtel est idéalement situé entre les pyramides de Gizeh et le nouveau Grand Musée Égyptien. Il dispose de chambres modernes, d\'une grande piscine et de diverses options de restauration, ce qui en fait un point de départ idéal pour explorer les merveilles antiques de Gizeh.', ar: 'يتمتع هذا الفندق بموقع مثالي بين أهرامات الجيزة والمتحف المصري الكبير الجديد. ويضم غرفًا عصرية ومسبحًا كبيرًا وخيارات متنوعة لتناول الطعام، مما يجعله قاعدة مثالية لاستكشاف عجائب الجيزة القديمة.', it: 'Questo hotel è situato in una posizione ideale tra le Piramidi di Giza e il nuovo Grande Museo Egizio. Dispone di camere moderne, una grande piscina e varie opzioni di ristorazione, che lo rendono una base perfetta per esplorare le antiche meraviglie di Giza.', de: 'Dieses Hotel liegt ideal zwischen den Pyramiden von Gizeh und dem neuen Großen Ägyptischen Museum. Es verfügt über moderne Zimmer, einen großen Swimmingpool und verschiedene gastronomische Einrichtungen und ist somit ein perfekter Ausgangspunkt für die Erkundung der antiken Wunder von Gizeh.', ru: 'Этот отель идеально расположен между пирамидами Гизы и новым Большим Египетским музеем. К услугам гостей современные номера, большой бассейн и различные рестораны, что делает его идеальной базой для изучения древних чудес Гизы.' },
        rating: 4.6,
        averagePrice: '$$$',
        googleMapsUrl: 'https://maps.app.goo.gl/d5bZ2a6xJ7j6k8F99',
        contactNumber: '+20 2 33778000'
      },
    ]
  },
  luxor: {
    id: 'luxor',
    name: { en: 'Luxor', fr: 'Louxor', ar: 'الأقصر', it: 'Luxor', de: 'Luxor', ru: 'Луксор' },
    heritage: [
      {
        id: 'lux-h-1',
        name: { en: 'Karnak Temple Complex', fr: 'Complexe du temple de Karnak', ar: 'مجمع معابد الكرنك', it: 'Complesso del tempio di Karnak', de: 'Karnak-Tempelkomplex', ru: 'Карнакский храмовый комплекс' },
        images: ['https://images.picsum.photos/id/50/1024/768.jpg', 'https://images.picsum.photos/id/51/1024/768.jpg'],
        shortDescription: { en: 'A vast mix of decayed temples, chapels, pylons, and other buildings.', fr: 'Un vaste mélange de temples en ruines, de chapelles, de pylônes et d\'autres bâtiments.', ar: 'مزيج واسع من المعابد المتهالكة والمصليات والأبراج والمباني الأخرى.', it: 'Un vasto insieme di templi in rovina, cappelle, piloni e altri edifici.', de: 'Eine riesige Mischung aus verfallenen Tempeln, Kapellen, Pylonen und anderen Gebäuden.', ru: 'Огромный комплекс полуразрушенных храмов, часовен, пилонов и других строений.' },
        longDescription: { en: 'The Karnak Temple Complex comprises a vast mix of decayed temples, chapels, pylons, and other buildings near Luxor, in Egypt. Construction at the complex began during the reign of Senusret I in the Middle Kingdom and continued into the Ptolemaic period. It is a vast open-air museum and the second largest ancient religious site in the world.', fr: 'Le complexe du temple de Karnak comprend un vaste mélange de temples en ruines, de chapelles, de pylônes et d\'autres bâtiments près de Louxor, en Égypte. La construction du complexe a commencé sous le règne de Sésostris Ier au Moyen Empire et s\'est poursuivie jusqu\'à l\'époque ptolémaïque. C\'est un vaste musée en plein air et le deuxième plus grand site religieux antique au monde.', ar: 'يضم مجمع معابد الكرنك مزيجًا واسعًا من المعابد المتهالكة والمصليات والأبراج والمباني الأخرى بالقرب من الأقصر في مصر. بدأ بناء المجمع في عهد سنوسرت الأول في المملكة الوسطى واستمر حتى العصر البطلمي. إنه متحف ضخم في الهواء الطلق وثاني أكبر موقع ديني قديم في العالم.', it: 'Il Complesso del Tempio di Karnak comprende un vasto insieme di templi in rovina, cappelle, piloni e altri edifici vicino a Luxor, in Egitto. La costruzione del complesso iniziò durante il regno di Sesostri I nel Medio Regno e continuò nel periodo tolemaico. È un vasto museo a cielo aperto e il secondo sito religioso antico più grande del mondo.', de: 'Der Karnak-Tempelkomplex umfasst eine riesige Mischung aus verfallenen Tempeln, Kapellen, Pylonen und anderen Gebäuden in der Nähe von Luxor, Ägypten. Der Bau des Komplexes begann während der Herrschaft von Sesostris I. im Mittleren Reich und dauerte bis in die ptolemäische Zeit. Es ist ein riesiges Freilichtmuseum und die zweitgrößte antike religiöse Stätte der Welt.', ru: 'Карнакский храмовый комплекс представляет собой огромное смешение полуразрушенных храмов, часовен, пилонов и других зданий недалеко от Луксора в Египте. Строительство комплекса началось во время правления Сенусерта I в Среднем царстве и продолжалось до птолемеевского периода. Это огромный музей под открытым небом и второе по величине древнее религиозное место в мире.' },
        rating: 4.9,
        googleMapsUrl: 'https://maps.app.goo.gl/hG9jF8yE7zD6k4A8A',
        contactNumber: '+20 95 2370637'
      },
      {
        id: 'lux-h-2',
        name: { en: 'Valley of the Kings', fr: 'Vallée des Rois', ar: 'وادي الملوك', it: 'Valle dei Re', de: 'Tal der Könige', ru: 'Долина Царей' },
        images: ['https://images.picsum.photos/id/141/1024/768.jpg', 'https://images.picsum.photos/id/142/1024/768.jpg'],
        shortDescription: { en: 'The principal burial place of the major royal figures of the Egyptian New Kingdom.', fr: 'Le principal lieu de sépulture des grandes figures royales du Nouvel Empire égyptien.', ar: 'مكان الدفن الرئيسي للشخصيات الملكية الكبرى في الدولة المصرية الحديثة.', it: 'Il principale luogo di sepoltura delle maggiori figure reali del Nuovo Regno egizio.', de: 'Die Hauptgrablege der bedeutenden königlichen Persönlichkeiten des ägyptischen Neuen Reiches.', ru: 'Основное место захоронения главных царских особ египетского Нового царства.' },
        longDescription: { en: 'For a period of nearly 500 years from the 16th to 11th century BC, rock-cut tombs were excavated for the pharaohs and powerful nobles of the New Kingdom. The valley contains 63 tombs and chambers, including the famous tomb of Tutankhamun, renowned for its well-preserved artifacts.', fr: 'Pendant une période de près de 500 ans, du XVIe au XIe siècle avant J.-C., des tombes taillées dans la roche ont été creusées pour les pharaons et les puissants nobles du Nouvel Empire. La vallée contient 63 tombes et chambres, dont la célèbre tombe de Toutankhamon, réputée pour ses objets bien conservés.', ar: 'على مدى ما يقرب من 500 عام من القرن السادس عشر إلى القرن الحادي عشر قبل الميلاد، تم حفر مقابر مقطوعة في الصخر للفراعنة والنبلاء الأقوياء في الدولة الحديثة. ويحتوي الوادي على 63 مقبرة وغرفة، بما في ذلك مقبرة توت عنخ آمون الشهيرة، التي تشتهر بآثارها المحفوظة جيدًا.', it: 'Per un periodo di quasi 500 anni, dal XVI all\'XI secolo a.C., furono scavate tombe rupestri per i faraoni e i potenti nobili del Nuovo Regno. La valle contiene 63 tombe e camere, inclusa la famosa tomba di Tutankhamon, rinomata per i suoi manufatti ben conservati.', de: 'Für einen Zeitraum von fast 500 Jahren vom 16. bis zum 11. Jahrhundert v. Chr. wurden Felsengräber für die Pharaonen und mächtigen Adligen des Neuen Reiches ausgehoben. Das Tal enthält 63 Gräber und Kammern, darunter das berühmte Grab von Tutanchamun, das für seine gut erhaltenen Artefakte bekannt ist.', ru: 'На протяжении почти 500 лет, с 16 по 11 век до н.э., для фараонов и могущественных вельмож Нового царства высекались гробницы в скалах. Долина насчитывает 63 гробницы и камеры, включая знаменитую гробницу Тутанхамона, известную своими хорошо сохранившимися артефактами.' },
        rating: 4.9,
        googleMapsUrl: 'https://maps.app.goo.gl/rG8z9V7HjL6tW5m6A',
      },
    ],
    restaurants: [],
    cafes: [],
    hotels: []
  },
  aswan: { 
    id: 'aswan', 
    name: { en: 'Aswan', fr: 'Assouan', ar: 'أسوان', it: 'Aswan', de: 'Assuan', ru: 'Асуан' }, 
    heritage: [
        {
        id: 'asw-h-1',
        name: { en: 'Philae Temple', fr: 'Temple de Philæ', ar: 'معبد فيلة', it: 'Tempio di File', de: 'Philae-Tempel', ru: 'Храм Филе' },
        images: ['https://images.picsum.photos/id/151/1024/768.jpg', 'https://images.picsum.photos/id/152/1024/768.jpg'],
        shortDescription: { en: 'An island-based temple complex dedicated to the goddess Isis.', fr: 'Un complexe de temples insulaire dédié à la déesse Isis.', ar: 'مجمع معابد قائم على جزيرة مخصص للإلهة إيزيس.', it: 'Un complesso di templi su un\'isola dedicato alla dea Iside.', de: 'Ein Inseltempelkomplex, der der Göttin Isis gewidmet ist.', ru: 'Храмовый комплекс на острове, посвященный богине Исиде.' },
        longDescription: { en: 'Originally located on Philae Island, the temple was relocated to Agilkia Island after the construction of the Aswan High Dam threatened to submerge it. The temple is a stunning example of Ptolemaic architecture and can only be reached by boat, making the visit a memorable experience.', fr: 'Initialement situé sur l\'île de Philæ, le temple a été déplacé sur l\'île d\'Agilkia après que la construction du haut barrage d\'Assouan ait menacé de le submerger. Le temple est un exemple magnifique de l\'architecture ptolémaïque et ne peut être atteint que par bateau, ce qui rend la visite une expérience mémorable.', ar: 'كان المعبد يقع في الأصل في جزيرة فيلة، وقد تم نقله إلى جزيرة أجيلكيا بعد أن هدد بناء السد العالي في أسوان بإغراقه. المعبد مثال مذهل على العمارة البطلمية ولا يمكن الوصول إليه إلا عن طريق القوارب، مما يجعل الزيارة تجربة لا تنسى.', it: 'Originariamente situato sull\'isola di File, il tempio è stato trasferito sull\'isola di Agilkia dopo che la costruzione della diga di Assuan minacciava di sommergerlo. Il tempio è uno splendido esempio di architettura tolemaica ed è raggiungibile solo in barca, rendendo la visita un\'esperienza memorabile.', de: 'Ursprünglich auf der Insel Philae gelegen, wurde der Tempel auf die Insel Agilkia verlegt, nachdem der Bau des Assuan-Hochdamms drohte, ihn zu überfluten. Der Tempel ist ein atemberaubendes Beispiel ptolemäischer Architektur und kann nur mit dem Boot erreicht werden, was den Besuch zu einem unvergesslichen Erlebnis macht.', ru: 'Изначально расположенный на острове Филе, храм был перенесен на остров Агилкия после того, как строительство Асуанской плотины угрожало его затоплением. Храм является потрясающим примером птолемеевской архитектуры, и добраться до него можно только на лодке, что делает посещение незабываемым.' },
        rating: 4.8,
        googleMapsUrl: 'https://maps.app.goo.gl/6L8mJ5N4KqP7rX2Y8',
        },
    ], 
    restaurants: [], 
    cafes: [], 
    hotels: [] 
  },
  alexandria: { 
    id: 'alexandria', 
    name: { en: 'Alexandria', fr: 'Alexandrie', ar: 'الإسكندرية', it: 'Alessandria', de: 'Alexandria', ru: 'Александрия' }, 
    heritage: [
        {
        id: 'alex-h-1',
        name: { en: 'Bibliotheca Alexandrina', fr: 'Bibliotheca Alexandrina', ar: 'مكتبة الإسكندرية', it: 'Bibliotheca Alexandrina', de: 'Bibliotheca Alexandrina', ru: 'Библиотека Александрина' },
        images: ['https://images.picsum.photos/id/161/1024/768.jpg', 'https://images.picsum.photos/id/162/1024/768.jpg'],
        shortDescription: { en: 'A modern library and cultural center, commemorating the ancient Library of Alexandria.', fr: 'Une bibliothèque et un centre culturel modernes, commémorant l\'ancienne Bibliothèque d\'Alexandrie.', ar: 'مكتبة ومركز ثقافي حديث، إحياء لذكرى مكتبة الإسكندرية القديمة.', it: 'Una moderna biblioteca e centro culturale, che commemora l\'antica Biblioteca di Alessandria.', de: 'Eine moderne Bibliothek und ein Kulturzentrum zum Gedenken an die antike Bibliothek von Alexandria.', ru: 'Современная библиотека и культурный центр, посвященные древней Александрийской библиотеке.' },
        longDescription: { en: 'The Bibliotheca Alexandrina is a major library and cultural center located on the shore of the Mediterranean Sea. It is a revival of the ancient Library of Alexandria and houses millions of books, museums, art galleries, and a planetarium. Its stunning modern architecture makes it a landmark of the city.', fr: 'La Bibliotheca Alexandrina est une grande bibliothèque et un centre culturel situés sur la rive de la mer Méditerranée. C\'est une renaissance de l\'ancienne Bibliothèque d\'Alexandrie et elle abrite des millions de livres, des musées, des galeries d\'art et un planétarium. Son architecture moderne époustouflante en fait un point de repère de la ville.', ar: 'مكتبة الإسكندرية هي مكتبة ومركز ثقافي كبير يقع على شاطئ البحر الأبيض المتوسط. وهي إحياء لمكتبة الإسكندرية القديمة وتضم ملايين الكتب والمتاحف والمعارض الفنية والقبة السماوية. هندستها المعمارية الحديثة المذهلة تجعلها معلماً من معالم المدينة.', it: 'La Bibliotheca Alexandrina è una grande biblioteca e centro culturale situato sulla riva del Mar Mediterraneo. È una rinascita dell\'antica Biblioteca di Alessandria e ospita milioni di libri, musei, gallerie d\'arte e un planetario. La sua straordinaria architettura moderna la rende un punto di riferimento della città.', de: 'Die Bibliotheca Alexandrina ist eine bedeutende Bibliothek und ein Kulturzentrum an der Küste des Mittelmeers. Sie ist eine Wiederbelebung der antiken Bibliothek von Alexandria und beherbergt Millionen von Büchern, Museen, Kunstgalerien und ein Planetarium. Ihre atemberaubende moderne Architektur macht sie zu einem Wahrzeichen der Stadt.', ru: 'Библиотека Александрина — это крупная библиотека и культурный центр, расположенный на берегу Средиземного моря. Она является возрождением древней Александрийской библиотеки и вмещает миллионы книг, музеи, художественные галереи и планетарий. Ее потрясающая современная архитектура делает ее достопримечательностью города.' },
        rating: 4.8,
        googleMapsUrl: 'https://maps.app.goo.gl/Rk4zF7j3pX5G8yB9A',
        contactNumber: '+20 3 4839999'
      },
    ], 
    restaurants: [], 
    cafes: [], 
    hotels: [] 
  },
  sharm_el_sheikh: { id: 'sharm_el_sheikh', name: { en: 'Sharm El-Sheikh', fr: 'Charm el-Cheikh', ar: 'شرم الشيخ', it: 'Sharm El-Sheikh', de: 'Scharm El-Scheich', ru: 'Шарм-эш-Шейх' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  hurghada: { id: 'hurghada', name: { en: 'Hurghada', fr: 'Hurghada', ar: 'الغردقة', it: 'Hurghada', de: 'Hurghada', ru: 'Хургада' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  suez: { id: 'suez', name: { en: 'Suez', fr: 'Suez', ar: 'السويس', it: 'Suez', de: 'Sues', ru: 'Суэц' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  port_said: { id: 'port_said', name: { en: 'Port Said', fr: 'Port-Saïd', ar: 'بورسعيد', it: 'Port Said', de: 'Port Said', ru: 'Порт-Саид' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  ismailia: { id: 'ismailia', name: { en: 'Ismailia', fr: 'Ismaïlia', ar: 'الإسماعيلية', it: 'Ismailia', de: 'Ismailia', ru: 'Исмаилия' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  damietta: { id: 'damietta', name: { en: 'Damietta', fr: 'Damiette', ar: 'دمياط', it: 'Damietta', de: 'Damietta', ru: 'Думьят' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  marsa_matrouh: { id: 'marsa_matrouh', name: { en: 'Marsa Matrouh', fr: 'Marsa Matrouh', ar: 'مرسى مطروح', it: 'Marsa Matruh', de: 'Marsa Matruh', ru: 'Мерса-Матрух' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  fayoum: { id: 'fayoum', name: { en: 'Fayoum', fr: 'Fayoum', ar: 'الفيوم', it: 'Fayyum', de: 'Fayyum', ru: 'Файюм' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  minya: { id: 'minya', name: { en: 'Minya', fr: 'Minya', ar: 'المنيا', it: 'Minya', de: 'Minya', ru: 'Минья' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  assiut: { id: 'assiut', name: { en: 'Assiut', fr: 'Assiout', ar: 'أسيوط', it: 'Asyut', de: 'Asyut', ru: 'Асьют' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  beni_suef: { id: 'beni_suef', name: { en: 'Beni Suef', fr: 'Beni Souef', ar: 'بني سويف', it: 'Beni Suef', de: 'Beni Suef', ru: 'Бени-Суэйф' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  kafr_el_sheikh: { id: 'kafr_el_sheikh', name: { en: 'Kafr El Sheikh', fr: 'Kafr el-Cheikh', ar: 'كفر الشيخ', it: 'Kafr El Sheikh', de: 'Kafr El-Sheikh', ru: 'Кафр-эш-Шейх' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
  sohag: { id: 'sohag', name: { en: 'Sohag', fr: 'Sohag', ar: 'سوهاج', it: 'Sohag', de: 'Sohag', ru: 'Сохаг' }, heritage: [], restaurants: [], cafes: [], hotels: [] },
};

// UI translations
export const UI_TRANSLATIONS: Translations = {
  en: {
    appName: "TourMate Egypt",
    welcomeMessage: "Your personal guide to exploring the wonders of Egypt. Select your governorate to begin.",
    selectGovernorate: "Select a Governorate",
    start: "Start",
    heritageSites: "Heritage Sites",
    restaurants: "Restaurants",
    cafes: "Cafés",
    hotels: "Hotels",
    viewDetails: "View Details",
    searchPlaceholder: "Search for a place...",
    rating: "Rating",
    averagePrice: "Average Price",
    contact: "Contact",
    listenDescription: "Listen to Description",
    getDirections: "Get Directions",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove from Favorites",
    share: "Share",
    maleVoice: "Male Voice",
    femaleVoice: "Female Voice",
    favorites: "Favorites",
    myFavorites: "My Favorites",
    noFavorites: "You haven't added any favorites yet.",
    about: "About",
    aboutTourMate: "About TourMate Egypt",
    aboutText: "TourMate Egypt is a passion project designed to make exploring Egypt's rich culture and history easier and more immersive for tourists. It provides curated lists of significant places across various governorates, complete with details, multilingual support, and interactive features.",
    changeGovernorate: "Change Governorate",
    addedToFavorites: "Added to favorites!",
    removedFromFavorites: "Removed from favorites!",
    close: "Close",
    back: "Back",
    settings: "Settings",
    language: "Language",
    appearance: "Appearance",
    lightTheme: "Light",
    darkTheme: "Dark",
    governorate: "Governorate",
  },
  fr: {
    appName: "TourMate Égypte",
    welcomeMessage: "Votre guide personnel pour explorer les merveilles de l'Égypte. Sélectionnez votre gouvernorat pour commencer.",
    selectGovernorate: "Sélectionnez un gouvernorat",
    start: "Commencer",
    heritageSites: "Sites du patrimoine",
    restaurants: "Restaurants",
    cafes: "Cafés",
    hotels: "Hôtels",
    viewDetails: "Voir les détails",
    searchPlaceholder: "Rechercher un lieu...",
    rating: "Évaluation",
    averagePrice: "Prix moyen",
    contact: "Contact",
    listenDescription: "Écouter la description",
    getDirections: "Obtenir l'itinéraire",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    share: "Partager",
    maleVoice: "Voix masculine",
    femaleVoice: "Voix féminine",
    favorites: "Favoris",
    myFavorites: "Mes favoris",
    noFavorites: "Vous n'avez pas encore ajouté de favoris.",
    about: "À propos",
    aboutTourMate: "À propos de TourMate Égypte",
    aboutText: "TourMate Égypte est un projet passionné conçu pour rendre l'exploration de la riche culture et de l'histoire de l'Égypte plus facile et plus immersive pour les touristes. Il fournit des listes organisées de lieux importants dans divers gouvernorats, avec des détails, un support multilingue et des fonctionnalités interactives.",
    changeGovernorate: "Changer de gouvernorat",
    addedToFavorites: "Ajouté aux favoris !",
    removedFromFavorites: "Retiré des favoris !",
    close: "Fermer",
    back: "Retour",
    settings: "Paramètres",
    language: "Langue",
    appearance: "Apparence",
    lightTheme: "Clair",
    darkTheme: "Sombre",
    governorate: "Gouvernorat",
  },
  ar: {
    appName: "رفيق السفر مصر",
    welcomeMessage: "دليلك الشخصي لاستكشاف عجائب مصر. اختر محافظتك للبدء.",
    selectGovernorate: "اختر محافظة",
    start: "ابدأ",
    heritageSites: "مواقع تراثية",
    restaurants: "مطاعم",
    cafes: "مقاهي",
    hotels: "فنادق",
    viewDetails: "عرض التفاصيل",
    searchPlaceholder: "ابحث عن مكان...",
    rating: "التقييم",
    averagePrice: "متوسط السعر",
    contact: "للتواصل",
    listenDescription: "استمع للوصف",
    getDirections: "احصل على الاتجاهات",
    addToFavorites: "أضف إلى المفضلة",
    removeFromFavorites: "إزالة من المفضلة",
    share: "مشاركة",
    maleVoice: "صوت رجالي",
    femaleVoice: "صوت نسائي",
    favorites: "المفضلة",
    myFavorites: "مفضلتي",
    noFavorites: "لم تقم بإضافة أي أماكن مفضلة بعد.",
    about: "حول",
    aboutTourMate: "حول رفيق السفر مصر",
    aboutText: "رفيق السفر مصر هو مشروع تم تطويره بشغف لجعل استكشاف ثقافة مصر وتاريخها الغني أكثر سهولة ومتعة للسياح. يوفر قوائم منسقة للأماكن الهامة عبر مختلف المحافظات، مع تفاصيل كاملة ودعم متعدد اللغات وميزات تفاعلية.",
    changeGovernorate: "تغيير المحافظة",
    addedToFavorites: "تمت الإضافة إلى المفضلة!",
    removedFromFavorites: "تمت الإزالة من المفضلة!",
    close: "إغلاق",
    back: "رجوع",
    settings: "الإعدادات",
    language: "اللغة",
    appearance: "المظهر",
    lightTheme: "فاتح",
    darkTheme: "داكن",
    governorate: "المحافظة",
  },
  it: {
    appName: "TourMate Egitto",
    welcomeMessage: "La tua guida personale per esplorare le meraviglie dell'Egitto. Seleziona il tuo governatorato per iniziare.",
    selectGovernorate: "Seleziona un Governatorato",
    start: "Inizia",
    heritageSites: "Siti del Patrimonio",
    restaurants: "Ristoranti",
    cafes: "Caffè",
    hotels: "Hotel",
    viewDetails: "Vedi Dettagli",
    searchPlaceholder: "Cerca un luogo...",
    rating: "Valutazione",
    averagePrice: "Prezzo Medio",
    contact: "Contatto",
    listenDescription: "Ascolta la Descrizione",
    getDirections: "Ottieni Indicazioni",
    addToFavorites: "Aggiungi ai Preferiti",
    removeFromFavorites: "Rimuovi dai Preferiti",
    share: "Condividi",
    maleVoice: "Voce Maschile",
    femaleVoice: "Voce Femminile",
    favorites: "Preferiti",
    myFavorites: "I Miei Preferiti",
    noFavorites: "Non hai ancora aggiunto nessun preferito.",
    about: "Informazioni",
    aboutTourMate: "Informazioni su TourMate Egitto",
    aboutText: "TourMate Egitto è un progetto passionale progettato per rendere l'esplorazione della ricca cultura e storia dell'Egitto più facile e coinvolgente per i turisti. Fornisce elenchi curati di luoghi significativi in vari governatorati, completi di dettagli, supporto multilingue e funzionalità interattive.",
    changeGovernorate: "Cambia Governatorato",
    addedToFavorites: "Aggiunto ai preferiti!",
    removedFromFavorites: "Rimosso dai preferiti!",
    close: "Chiudi",
    back: "Indietro",
    settings: "Impostazioni",
    language: "Lingua",
    appearance: "Aspetto",
    lightTheme: "Chiaro",
    darkTheme: "Scuro",
    governorate: "Governatorato",
  },
  de: {
    appName: "TourMate Ägypten",
    welcomeMessage: "Ihr persönlicher Führer zur Erkundung der Wunder Ägyptens. Wählen Sie Ihr Gouvernement, um zu beginnen.",
    selectGovernorate: "Wählen Sie ein Gouvernement",
    start: "Start",
    heritageSites: "Kulturerbestätten",
    restaurants: "Restaurants",
    cafes: "Cafés",
    hotels: "Hotels",
    viewDetails: "Details anzeigen",
    searchPlaceholder: "Suche nach einem Ort...",
    rating: "Bewertung",
    averagePrice: "Durchschnittspreis",
    contact: "Kontakt",
    listenDescription: "Beschreibung anhören",
    getDirections: "Route berechnen",
    addToFavorites: "Zu Favoriten hinzufügen",
    removeFromFavorites: "Aus Favoriten entfernen",
    share: "Teilen",
    maleVoice: "Männliche Stimme",
    femaleVoice: "Weibliche Stimme",
    favorites: "Favoriten",
    myFavorites: "Meine Favoriten",
    noFavorites: "Sie haben noch keine Favoriten hinzugefügt.",
    about: "Über",
    aboutTourMate: "Über TourMate Ägypten",
    aboutText: "TourMate Ägypten ist ein Leidenschaftsprojekt, das entwickelt wurde, um Touristen die Erkundung der reichen Kultur und Geschichte Ägyptens einfacher und intensiver zu gestalten. Es bietet kuratierte Listen bedeutender Orte in verschiedenen Gouvernements, komplett mit Details, mehrsprachiger Unterstützung und interaktiven Funktionen.",
    changeGovernorate: "Gouvernement wechseln",
    addedToFavorites: "Zu Favoriten hinzugefügt!",
    removedFromFavorites: "Aus Favoriten entfernt!",
    close: "Schließen",
    back: "Zurück",
    settings: "Einstellungen",
    language: "Sprache",
    appearance: "Erscheinungsbild",
    lightTheme: "Hell",
    darkTheme: "Dunkel",
    governorate: "Gouvernement",
  },
  ru: {
    appName: "ТурМейт Египет",
    welcomeMessage: "Ваш личный гид по изучению чудес Египта. Выберите свою провинцию, чтобы начать.",
    selectGovernorate: "Выберите провинцию",
    start: "Начать",
    heritageSites: "Объекты наследия",
    restaurants: "Рестораны",
    cafes: "Кафе",
    hotels: "Отели",
    viewDetails: "Посмотреть детали",
    searchPlaceholder: "Поиск места...",
    rating: "Рейтинг",
    averagePrice: "Средняя цена",
    contact: "Контакт",
    listenDescription: "Прослушать описание",
    getDirections: "Проложить маршрут",
    addToFavorites: "Добавить в избранное",
    removeFromFavorites: "Удалить из избранного",
    share: "Поделиться",
    maleVoice: "Мужской голос",
    femaleVoice: "Женский голос",
    favorites: "Избранное",
    myFavorites: "Мое избранное",
    noFavorites: "Вы еще не добавили ничего в избранное.",
    about: "О приложении",
    aboutTourMate: "О ТурМейт Египет",
    aboutText: "ТурМейт Египет — это проект, созданный с любовью, чтобы сделать изучение богатой культуры и истории Египта проще и увлекательнее для туристов. Он предоставляет тщательно подобранные списки значимых мест в различных провинциях, с подробной информацией, многоязычной поддержкой и интерактивными функциями.",
    changeGovernorate: "Сменить провинцию",
    addedToFavorites: "Добавлено в избранное!",
    removedFromFavorites: "Удалено из избранного!",
    close: "Закрыть",
    back: "Назад",
    settings: "Настройки",
    language: "Язык",
    appearance: "Внешний вид",
    lightTheme: "Светлая",
    darkTheme: "Темная",
    governorate: "Провинция",
  },
};
